// sourced from this website: https://rentechdigital.com/smartscraper/business-report-details/canada/ontario/hamilton/restaurants

let restaurants = [
 {
   "name": "The Burnt Tongue",
   "address": "11 King St W, Dundas, ON L9H 1T5, Canada",
   "phone": "+1 289-238-8200",
   "email": "info@theburnttongue.com",
   "lat": 43.2662836,
   "lng": -79.9542766,
   "url": "http://www.theburnttongue.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.7,
   "rating_count": 108,
   "zip": "L9H 1T5",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants,Soup restaurants"
 },
 {
   "name": "Stonewalls Live Music Venue",
   "address": "339 York Blvd, Hamilton, ON L8R 2X9, Canada",
   "phone": "+1 905-577-0808",
   "email": "management@stonewallshamilton.com",
   "lat": 43.2630772,
   "lng": -79.8784117,
   "url": "http://www.stonewallshamilton.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4,
   "rating_count": 869,
   "zip": "L8R 2X9",
   "primary_category_name": "Restaurants",
   "category_name": "Meal deliveries,Live music venues,Cocktail bars,Sandwich shops,Pubs,Hamburger restaurants,Restaurants,Takeout restaurants,Bar & grills,Delivery Restaurants"
 },
 {
   "name": "Royal Paan",
   "address": "30 Rymal Rd E, Hamilton, ON L9B 1T7, Canada",
   "phone": "+1 365-366-7226",
   "email": "rprivermont@gmail.com",
   "lat": 43.2016524,
   "lng": -79.8915437,
   "url": "https://royalpaan.com/locations/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 3.3,
   "rating_count": 749,
   "zip": "L9B 1T7",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "The Burnt Tongue",
   "address": "10 Cannon St E, Hamilton, ON L8L 1Z5, Canada",
   "phone": "+1 905-536-1146",
   "email": "info@theburnttongue.com",
   "lat": 43.2605122,
   "lng": -79.866935,
   "url": "http://www.theburnttongue.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.6,
   "rating_count": 1007,
   "zip": "L8L 1Z5",
   "primary_category_name": "Restaurants",
   "category_name": "Soup restaurants,Restaurants"
 },
 {
   "name": "Just Jollof",
   "address": "92 Jackson St E, Hamilton, ON L8N 1L2, Canada",
   "phone": "+1 289-921-6244",
   "email": "905justjollof@gmail.com",
   "lat": 43.2534074,
   "lng": -79.8663062,
   "url": "https://www.justjollof.net/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.9,
   "rating_count": 17,
   "zip": "L8N 1L2",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Bistro at Marquis Gardens",
   "address": "1365 Sandhill Dr, Ancaster, ON L9G 4V5, Canada",
   "phone": "+1 905-304-8184",
   "email": "info@mgbistro.com",
   "lat": 43.1918246,
   "lng": -80.0283561,
   "url": "http://www.mgbistro.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 3.5,
   "rating_count": 11,
   "zip": "L9G 4V5",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Turtle Jack's Winona",
   "address": "1338 S Service Rd, Stoney Creek, ON L8E 5C4, Canada",
   "phone": "+1 289-639-8444",
   "email": "winona@turtlejacks.com",
   "lat": 43.216551,
   "lng": -79.641833,
   "url": "https://turtlejacks.com/locations/winona/?utm_source=G&utm_medium=LPM&utm_campaign=MTY",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.1,
   "rating_count": 1095,
   "zip": "L8E 5C4",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Victoria's Steak & Seafood",
   "address": "470 King St W, Hamilton, ON L8P 1B7, Canada",
   "phone": "+1 905-540-4771",
   "email": "brandon@carorestaurant.com",
   "lat": 43.2609189,
   "lng": -79.8832444,
   "url": "http://www.victoriasrestaurant.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.7,
   "rating_count": 471,
   "zip": "L8P 1B7",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "The Innsville Restaurant",
   "address": "1143 Hamilton, Regional Rd 8, Stoney Creek, ON L8E 5G7, Canada",
   "phone": "+1 905-643-1244",
   "email": "info@innsville.com",
   "lat": 43.209774,
   "lng": -79.6616194,
   "url": "http://innsville.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.5,
   "rating_count": 1224,
   "zip": "L8E 5G7",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Holy Shakes Hamilton",
   "address": "1299 Barton St E Unit K04, Hamilton, ON L8H 2V4, Canada",
   "phone": "+1 289-389-3979",
   "email": "hamilton@416hospitalitygroup.com",
   "lat": 43.2497794,
   "lng": -79.8073049,
   "url": "https://holyshakes.ca/locations/holy-shakes-hamilton/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4,
   "rating_count": 152,
   "zip": "L8H 2V4",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Conversate Steak and Seafood",
   "address": "38 King William St, Hamilton, ON L8R 3N8, Canada",
   "phone": "+1 905-525-3730",
   "email": "info@conversaterestaurant.ca",
   "lat": 43.256917,
   "lng": -79.8677336,
   "url": "http://www.conversaterestaurant.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.8,
   "rating_count": 147,
   "zip": "L8R 3N8",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Indian food point",
   "address": "804 Upper Gage Ave, Hamilton, ON L8V 4K4, Canada",
   "phone": "+1 289-941-0150",
   "email": "myindianfoodpoint@gmail.com",
   "lat": 43.2197939,
   "lng": -79.843078,
   "url": "https://indianfoodpoint.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.8,
   "rating_count": 241,
   "zip": "L8V 4K4",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Starwood Seafood & Grill",
   "address": "1686 Main St W, Hamilton, ON L8S 0A2, Canada",
   "phone": "+1 905-920-5084",
   "email": "info@starwoodseafoodandgrill.com",
   "lat": 43.2575334,
   "lng": -79.9344848,
   "url": "https://starwoodseafoodandgrill.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.4,
   "rating_count": 41,
   "zip": "L8S 0A2",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Wild Orchid Restaurant Downtown Hamilton",
   "address": "286 James St N, Hamilton, ON L8R 2L3, Canada",
   "phone": "+1 905-528-7171",
   "email": "info@wildorchidrestaurant.ca",
   "lat": 43.2635458,
   "lng": -79.8658906,
   "url": "http://www.wildorchidrestaurant.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.1,
   "rating_count": 548,
   "zip": "L8R 2L3",
   "primary_category_name": "Restaurants",
   "category_name": "Portuguese restaurants,Restaurants,Steak houses,Seafood restaurants,Cafes"
 },
 {
   "name": "Maisy’s Pearl Oyster Bar",
   "address": "342 Barton St E, Hamilton, ON L8L 2X7, Canada",
   "phone": "+1 289-389-1870",
   "email": "david@maisyspearl.com",
   "lat": 43.2603175,
   "lng": -79.8510649,
   "url": "https://www.maisyspearl.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 5,
   "rating_count": 7,
   "zip": "L8L 2X7",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Kamoosh Bistro",
   "address": "34 Main St N, Waterdown, ON L0R 2H0, Canada",
   "phone": "+1 289-895-7500",
   "email": "info@kamooshbistro.com",
   "lat": 43.3342377,
   "lng": -79.8937733,
   "url": "http://www.kamooshbistro.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.4,
   "rating_count": 324,
   "zip": "L0R 2H0",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Freshly Squeezed",
   "address": "999 Upper Wentworth St, Hamilton, ON L9A 4X5, Canada",
   "phone": "+1 647-923-7875",
   "email": "fs@freshlysqueezed.ca",
   "lat": 43.2174928,
   "lng": -79.8612281,
   "url": "http://www.freshlysqueezed.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.3,
   "rating_count": 150,
   "zip": "L9A 4X5",
   "primary_category_name": "Restaurants",
   "category_name": "Juice shops,Restaurants"
 },
 {
   "name": "Crack Me Up",
   "address": "2 King St W Unit 205, Hamilton, ON L8P 1A1, Canada",
   "phone": "+1 905-529-5838",
   "email": "info@crack-me-up.com",
   "lat": 43.2586194,
   "lng": -79.871165,
   "url": "http://www.crack-me-up.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 3.2,
   "rating_count": 113,
   "zip": "L8P 1A1",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Rapscallion and Co.",
   "address": "178 James St N, Hamilton, ON L8R 2L1, Canada",
   "phone": "+1 905-522-0088",
   "email": "JEFF@RAPANDCO.CA",
   "lat": 43.2611946,
   "lng": -79.866916,
   "url": "http://rapandco.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.7,
   "rating_count": 937,
   "zip": "L8R 2L1",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants,Bars"
 },
 {
   "name": "Fionn MacCool's",
   "address": "1786 Stone Church Rd E Unit 1, Hamilton, ON L8J 0K5, Canada",
   "phone": "+1 289-919-2422",
   "email": "security@foodtastic.ca",
   "lat": 43.1914024,
   "lng": -79.8112564,
   "url": "https://www.fionnmaccools.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.1,
   "rating_count": 1164,
   "zip": "L8J 0K5",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Wimpy's Diner",
   "address": "989 Fennell Ave E, Hamilton, ON L8T 1R1, Canada",
   "phone": "+1 289-755-3600",
   "email": "info@wimpysdiner.ca",
   "lat": 43.2284477,
   "lng": -79.8365307,
   "url": "http://wimpysdiner.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 3.9,
   "rating_count": 450,
   "zip": "L8T 1R1",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Munchies Coffee House & Barkery",
   "address": "1000 Upper Gage Ave #4, Hamilton, ON L8V 4R5, Canada",
   "phone": "+1 905-389-6067",
   "email": "munchiesreservations@gmail.com",
   "lat": 43.2141137,
   "lng": -79.8458974,
   "url": "http://www.munchiesbarkery.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.6,
   "rating_count": 380,
   "zip": "L8V 4R5",
   "primary_category_name": "Restaurants",
   "category_name": "Dessert restaurants,Breakfast restaurants,Meal deliveries,Bakery and Cake Shops,Family restaurants,Coffee shops,Coffee stores,Cafes,Brunch restaurants,Restaurants,Dog cafes,Delivery Restaurants,Bakeries"
 },
 {
   "name": "Milestones",
   "address": "771 Golf Links Rd, Ancaster, ON L9K 1L5, Canada",
   "phone": "+1 365-210-0050",
   "email": "info@milestonesrestaurants.com",
   "lat": 43.2261619,
   "lng": -79.9524307,
   "url": "http://www.milestonesrestaurants.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.3,
   "rating_count": 395,
   "zip": "L9K 1L5",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Willow Valley Golf Course",
   "address": "8475 English Church Rd E, Mount Hope, ON L0R 1W0, Canada",
   "phone": "+1 905-679-2703",
   "email": "info@willowvalleygolf.com",
   "lat": 43.164097,
   "lng": -79.9047626,
   "url": "http://www.willowvalleygolf.com/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.6,
   "rating_count": 657,
   "zip": "L0R 1W0",
   "primary_category_name": "Restaurants",
   "category_name": "Public golf courses,Golf courses,Restaurants"
 },
 {
   "name": "Shoeless Joe's Sports Grill",
   "address": "1183 Upper James St, Hamilton, ON L9C 3B2, Canada",
   "phone": "+1 905-383-5637",
   "email": "security@foodtastic.ca",
   "lat": 43.2162264,
   "lng": -79.8864967,
   "url": "http://www.shoelessjoes.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.2,
   "rating_count": 2203,
   "zip": "L9C 3B2",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants,Sports bars,Bar & grills,Canadian restaurants"
 },
 {
   "name": "Turtle Jack's Waterdown",
   "address": "255 Dundas St E, Waterdown, ON L0R 2H6, Canada",
   "phone": "+1 905-690-1787",
   "email": "waterdown@turtlejacks.com",
   "lat": 43.331012,
   "lng": -79.898629,
   "url": "https://turtlejacks.com/locations/waterdown/?utm_source=G&utm_medium=LPM&utm_campaign=MTY",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.2,
   "rating_count": 982,
   "zip": "L0R 2H6",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Alumni Memorial Hall",
   "address": "Alumni Memorial Hall, 1280 Main St W, Hamilton, ON L8S 4K1, Canada",
   "phone": "+1 905-525-9140 ext. 23246",
   "email": "cayoung@mcmaster.ca",
   "lat": 43.2640002,
   "lng": -79.9196403,
   "url": "https://amh.mcmaster.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.6,
   "rating_count": 57,
   "zip": "L8S 4K1",
   "primary_category_name": "Restaurants",
   "category_name": "Bars,Restaurants"
 },
 {
   "name": "The Diplomat",
   "address": "43 King William St, Hamilton, ON L8R 1A2, Canada",
   "phone": "+1 905-523-4343",
   "email": "events@equalparts.ca",
   "lat": 43.2571761,
   "lng": -79.8671129,
   "url": "http://thediplomat.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.5,
   "rating_count": 731,
   "zip": "L8R 1A2",
   "primary_category_name": "Restaurants",
   "category_name": "Lounges,Bars,Restaurants"
 },
 {
   "name": "The Squire - Pub on Locke",
   "address": "225 Locke St S, Hamilton, ON L8P 4B6, Canada",
   "phone": "+1 905-525-0225",
   "email": "locke@yeoldesquire.ca",
   "lat": 43.2540419,
   "lng": -79.8858584,
   "url": "https://yeoldesquire.ca/locke/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.4,
   "rating_count": 244,
   "zip": "L8P 4B6",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 },
 {
   "name": "Hangry Chicken",
   "address": "1374, 7 S Service Rd W Unit, Stoney Creek, ON L8E 5C5, Canada",
   "phone": "+1 905-643-6161",
   "email": "coop1@hangrychicken.ca",
   "lat": 43.2142753,
   "lng": -79.6400756,
   "url": "http://www.hangrychicken.ca/",
   "country": "Canada",
   "state": "Ontario",
   "city": "Hamilton",
   "star_count": 4.2,
   "rating_count": 199,
   "zip": "L8E 5C5",
   "primary_category_name": "Restaurants",
   "category_name": "Restaurants"
 }
]


export { restaurants }